'use client';
import '../styles/global.css';
import '../styles/customBootstrapStyles.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'antd/dist/reset.css';
import '../styles/customAntdStyles.css';
import '../styles/customMuiStyles.css';
import "react-responsive-carousel/lib/styles/carousel.min.css";
import '../styles/customCarouselStyles.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment';
import { SessionProvider } from 'next-auth/react';
import { ApolloProvider } from "@apollo/react-hooks";
import client from '../config/applloClient';
import { Toaster } from 'react-hot-toast';
import { Session } from "next-auth";

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  pageProps
}: {
  children: React.ReactNode,
  pageProps: { session: Session },
}) {
  return (
    <SessionProvider session={pageProps?.session}>
      <ApolloProvider client={client}>
        <html lang="en">
          <script src='httpa://accounts.google.com/gsi/client' async defer></script>
          <LocalizationProvider dateAdapter={AdapterMoment}>
            <body className={inter.className}>{children}</body>
          </LocalizationProvider>
        </html>

      </ApolloProvider>
    </SessionProvider>
  )
}

